version: '3'

services:
  translationserver:
    container_name: TranslationServer
    image: translationserver:1.0
    expose:
     - 7890
    ports:
     - 7890:7890
    volumes:
      - /local_harddrive/models/:/models/
      - /local_harddrive/app:/app/
    #command: uvicorn main:app --reload --port 7890 --host 127.0.0.1
    command: uvicorn main:app --reload --port 7890 --host 0.0.0.0
      #network_mode: "host"
