version: '3'

services:
  translationserver:
    container_name: TranslationServer
    image: translationserver:1.0
    expose:
     - 7890
    ports:
     - 7890:7890
    volumes:
      - /data/models/m2m100_418M:/models/m2m100
    command: uvicorn main:app --reload --port 7890 --host 127.0.0.1
    network_mode: "host"
